### PR TITLE
rewritten to Kotlin

### PR DESCRIPTION
**Pull request by nick2525**
Kotlin is still crude, but it is important to start use Kotlin from begin, it will be more difficult to switch to Kotlin, when there will be a lot of code

### CODE REVIEW

**Comment by grishka** [comment]
I hate expressive languages.

**Comment by fma1** [comment]
@nick2525 You generally shouldn't send an unsolicited PR, rewriting the language if the owner didn't want it.

**Comment by nick2525** [comment]
The pull requests are created so that the community can accept / reject them after weighing all the arguments.  Accordingly, there is nothing wrong with pulling pull requests.  The intention is not always clear from the description.  Sometimes it's easier to write code and discuss on a pull request.

**Comment by ifvictr** [comment]
Still, the author mentioned in the README that this app isn't meant to be a polished project. Just because a repository had been made public doesn't mean it's community-controlled.

You spent the better part of your day on changes that weren't ever going to make it onto the main branch. Not the best use of your time IMO.

**Comment by fma1** [comment]
https://twitter.com/hmemcpy/status/1363569662445850624

Also, as stated by someone else:

> Still, the author mentioned in the README that this app isn't meant to be a polished project. Just because a repository had been made public doesn't mean it's community-controlled.

> You spent the better part of your day on changes that weren't ever going to make it onto the main branch. Not the best use of your time IMO.

**Pull request closed without merging**
