### PR TITLE
Implement invitation by phone number

### PR DESCRIPTION
**Pull request by dvkolesnikov**
- Show number of available invites on the Profile screen
- Invite a user by their phone number without sharing your contact list

### CODE REVIEW

**Comment by bit-world** [comment]
Have you tried sending invites without sharing contacts?
originally had a similar implementation #144 but some users  (according to them) are banned for this

**Comment by dvkolesnikov** [comment]
> Have you tried sending invites without sharing contacts?
> originally had a similar implementation #144 but some users (according to them) are banned for this

I have successfully invited only 2 persons but it was less than hour ago. I've seen your PR #144 but I didn't know that sharing contacts is necessary. Probably, it's needed to be tested more thoroughly before merging.

**Comment by zm21** [comment]
> > Have you tried sending invites without sharing contacts?
> > originally had a similar implementation #144 but some users (according to them) are banned for this
> 
> I have successfully invited only 2 persons but it was less than hour ago. I've seen your PR #144 but I didn't know that sharing contacts is necessary. Probably, it's needed to be tested more thoroughly before merging.



> Have you tried sending invites without sharing contacts?
> originally had a similar implementation #144 but some users (according to them) are banned for this
I used your version 1.0.9 and for some reason I can't invite anyone. I receive notifications that I have 0 invitations. Why if I didn't invite anyone?

**Comment by zm21** [comment]
> Have you tried sending invites without sharing contacts?
> originally had a similar implementation #144 but some users (according to them) are banned for this




> > Have you tried sending invites without sharing contacts?
> > originally had a similar implementation #144 but some users (according to them) are banned for this
> 
> I have successfully invited only 2 persons but it was less than hour ago. I've seen your PR #144 but I didn't know that sharing contacts is necessary. Probably, it's needed to be tested more thoroughly before merging.



I used your version 1.0.9 and for some reason I can't invite anyone. I receive notifications that I have 0 invitations. Why if I didn't invite anyone?

**Comment by dvkolesnikov** [comment]
> 
> I used your version 1.0.9 and for some reason I can't invite anyone. I receive notifications that I have 0 invitations. Why if I didn't invite anyone?

I don't know for sure what is the rules of granting invitations to the user on the server side. Do I understand right that server returns `num_invites = 0` in the `/me` response for your user?

**Comment by zm21** [comment]
> > I used your version 1.0.9 and for some reason I can't invite anyone. I receive notifications that I have 0 invitations. Why if I didn't invite anyone?
> 
> I don't know for sure what is the rules of granting invitations to the user on the server side. Do I understand right that server returns `num_invites = 0` in the `/me` response for your user?

Yes

**Comment by dvkolesnikov** [comment]
> > I don't know for sure what is the rules of granting invitations to the user on the server side. Do I understand right that server returns `num_invites = 0` in the `/me` response for your user?
> 
> Yes

I've just got 3 new invitations in my profile. It looks like they grant them periodically (daily?). So, probably, you should just wait for some time.

**Comment by badmanbh** [comment]
where i can download 1.0.9 with this feature? I only find 1.0.8 apk (latest release)

**Comment by dvkolesnikov** [comment]
> where i can download 1.0.9 with this feature? I only find 1.0.8 apk (latest release)

You can build it by yourself ifyou have Android Studio installed or you should wait until the PR is reviewed and merged

@grishka could you, please, review the PR? It doesn't conflict with #144 but allows the user to invite others without sending the contact list to the server.

**Comment by yasser22269** [comment]
Y

**Pull request merged**
